spring.application.name=employee_api

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:migrations
spring.flyway.clean-disabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/neoflex
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
