alter table if exists employees
   drop constraint if exists FK_employee_passport_id;

drop table if exists employees cascade;

drop table if exists passports cascade;

create table employees (
    salary float4 not null,
    id bigint generated by default as identity,
    passport_id bigint unique,
    name varchar(255) not null,
    surname varchar(255) not null,
    primary key (id)
);

create table passports (
    number integer not null,
    series integer not null,
    date timestamp(6) not null,
    id bigint generated by default as identity,
    primary key (id)
);

alter table if exists employees
   add constraint FK_employee_passport_id
   foreign key (passport_id)
   references passports;